language: ruby
rvm: 2.0.0
before_install:
- travis_retry gem install bitballoon
- travis_retry gem install jekyll
script: jekyll build
after_success: bitballoon deploy _site --access-token=$BB_ACCESS_TOKEN --site-id=$BB_SITE_ID
branches:
  only:
  - master
env:
  global:
  - secure: i9J4/jT6uzJq7gI85y9fNKkMjE6kkgzoR5cp4ho9cMSsIpVwB8sci4/1UygyxQdmqXpU177DV4WjInh7+RgKGgbG1zhc9kL1+o8yzvhNAWSPKlBjhIsPv2ZnvY/Q14QGMsk1MYC+hpZ7ZpqqBgVchFy4j/zRHsNkThdXNw/9ibqKZRlI/JVvpKfjY5QhscY+MR1e6RwvqIKyQidWb9t1VMJa/zT+H9TwK5uE/0wNq0jSRBaK1xhuMvAM9FFhaC0g0HcZpucFW6/ByyBYY/lsoZudoe+WLeVh4bhr1KhoT72VKcWg/VCf6RqH3m4zXPZUh+NiKAXYmg+hTtQNbNvTXTVt4/Exbqasr25ct2ZoTUJqwF8XgfFArJtwkoA4s4USGe55UElUYm+4RFSrjTcaC/co++v+Q6Nq1TXfsRCIQupfifD/pzPGpNNhGC+lOWYh0/sO+YGoWhBM8qBhkZi1jYsnb1SduAcAGdf6L8x/0u617X+klevhya9z7GG2A61DKDXWyjWeteWnwHac4AwATSj/bjXLNneOkV8yCiJ+JW1zrUqoyIdQRMhw0IH+FLOmsjfmE/R9b7Dnu2lp+H+q96ryItsSx6klPVnpnTRzX9lAUfUxw9qDGzXPvV4VHar92zXlZwPytxOKOZmnLTJLbGaodssjc3VJHBLZ46QdixU=
  - secure: VlnyTYg5hop2UAVbUaeVwYnHiutsYUq7TdLN4VbY0sc7A9jw/CdpLOd1/3BdMtoorKC5wuP0TMW6V//gCl51Wq4sqgpW5c4nk8PVHJh2CMuk63YSmclTiej513tC9yBZoLjwauh6v6I9vQKQYFtcnv3EBoldSxrkDSWhwMuHos9YPrUdmkgQUyj6SPqraQJAnc51eqJnp7t+XoY6SEoH1lwc75A6JWW8780QPhkbhK24VDM2laATXjpkEy8OMucJp1bNUyJ0wrZDrYNn08j0XFcgdc5TN7ywHWmaugefXbEj8drqTybakd7tHk1ROJPi1k8Hjvl9K3poxL1xYW6Ez1OOxuHJOAGZRrsfD3ozKxXDUbrtASRLWgtvkVHmZKBG1EwppvEHVp7B8ryulC1w0+WLenoSI0lBKeegwwIyD9zwzV1yV/HnS1K1XQyHY1+NhhjMCg6Z/CXK93pR6CSnV24xnpGS41MVYnq2UBAuCxCYXLFQ7y9S/8Zte8yM0GhAgSNNDjtg2NUIngv6/HlZuuc8C+VPq9PdpgYHi51QDfxueQURz3Y8zYI3TJC38FG8d7aDEbx/HJbBsfgwcmzb2w4YwUsyB1jjCjyuwayD9b3jsjCCfdZfyrE4r4ZYWq7Vfk913V2V9eH1F05jFSzRMzEuMgE2FcSez2cW4Hzn/QY=
